package com.bawei.database.My.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.data_resource.bean.FoodBean;
import com.bawei.data_resource.bean.GiftBean;
import com.bawei.data_resource.bean.QuickBean;

import com.bawei.database.My.db.FoodBeanDao;
import com.bawei.database.My.db.GiftBeanDao;
import com.bawei.database.My.db.QuickBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig foodBeanDaoConfig;
    private final DaoConfig giftBeanDaoConfig;
    private final DaoConfig quickBeanDaoConfig;

    private final FoodBeanDao foodBeanDao;
    private final GiftBeanDao giftBeanDao;
    private final QuickBeanDao quickBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        foodBeanDaoConfig = daoConfigMap.get(FoodBeanDao.class).clone();
        foodBeanDaoConfig.initIdentityScope(type);

        giftBeanDaoConfig = daoConfigMap.get(GiftBeanDao.class).clone();
        giftBeanDaoConfig.initIdentityScope(type);

        quickBeanDaoConfig = daoConfigMap.get(QuickBeanDao.class).clone();
        quickBeanDaoConfig.initIdentityScope(type);

        foodBeanDao = new FoodBeanDao(foodBeanDaoConfig, this);
        giftBeanDao = new GiftBeanDao(giftBeanDaoConfig, this);
        quickBeanDao = new QuickBeanDao(quickBeanDaoConfig, this);

        registerDao(FoodBean.class, foodBeanDao);
        registerDao(GiftBean.class, giftBeanDao);
        registerDao(QuickBean.class, quickBeanDao);
    }
    
    public void clear() {
        foodBeanDaoConfig.clearIdentityScope();
        giftBeanDaoConfig.clearIdentityScope();
        quickBeanDaoConfig.clearIdentityScope();
    }

    public FoodBeanDao getFoodBeanDao() {
        return foodBeanDao;
    }

    public GiftBeanDao getGiftBeanDao() {
        return giftBeanDao;
    }

    public QuickBeanDao getQuickBeanDao() {
        return quickBeanDao;
    }

}
