package com.bawei.database.My.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bawei.data_resource.bean.GiftBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GIFT_BEAN".
*/
public class GiftBeanDao extends AbstractDao<GiftBean, Long> {

    public static final String TABLENAME = "GIFT_BEAN";

    /**
     * Properties of entity GiftBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Myid = new Property(0, long.class, "myid", true, "_id");
        public final static Property Id = new Property(1, int.class, "id", false, "ID");
        public final static Property Giftname = new Property(2, String.class, "giftname", false, "GIFTNAME");
        public final static Property Giftpath = new Property(3, String.class, "giftpath", false, "GIFTPATH");
        public final static Property Price = new Property(4, int.class, "price", false, "PRICE");
    }


    public GiftBeanDao(DaoConfig config) {
        super(config);
    }
    
    public GiftBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GIFT_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: myid
                "\"ID\" INTEGER NOT NULL ," + // 1: id
                "\"GIFTNAME\" TEXT," + // 2: giftname
                "\"GIFTPATH\" TEXT," + // 3: giftpath
                "\"PRICE\" INTEGER NOT NULL );"); // 4: price
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GIFT_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GiftBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getMyid());
        stmt.bindLong(2, entity.getId());
 
        String giftname = entity.getGiftname();
        if (giftname != null) {
            stmt.bindString(3, giftname);
        }
 
        String giftpath = entity.getGiftpath();
        if (giftpath != null) {
            stmt.bindString(4, giftpath);
        }
        stmt.bindLong(5, entity.getPrice());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GiftBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getMyid());
        stmt.bindLong(2, entity.getId());
 
        String giftname = entity.getGiftname();
        if (giftname != null) {
            stmt.bindString(3, giftname);
        }
 
        String giftpath = entity.getGiftpath();
        if (giftpath != null) {
            stmt.bindString(4, giftpath);
        }
        stmt.bindLong(5, entity.getPrice());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public GiftBean readEntity(Cursor cursor, int offset) {
        GiftBean entity = new GiftBean( //
            cursor.getLong(offset + 0), // myid
            cursor.getInt(offset + 1), // id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // giftname
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // giftpath
            cursor.getInt(offset + 4) // price
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GiftBean entity, int offset) {
        entity.setMyid(cursor.getLong(offset + 0));
        entity.setId(cursor.getInt(offset + 1));
        entity.setGiftname(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGiftpath(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPrice(cursor.getInt(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GiftBean entity, long rowId) {
        entity.setMyid(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GiftBean entity) {
        if(entity != null) {
            return entity.getMyid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GiftBean entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
